using System;
using System.Diagnostics;
using System.IO;
using System.Runtime.InteropServices;
using Microsoft.Win32;

namespace App.UI;

/// <summary>
/// Registers the file types Epic RPF can open under the current user (HKCU\Software\
/// Classes — no admin needed) so double-clicking one launches the app with the file AND
/// so each extension shows its OWN icon on the desktop (the same icon it has in the tool).
///
/// Each extension gets a dedicated ProgId (EpicRpf.&lt;ext&gt;) whose DefaultIcon points at
/// wwwroot/icons/&lt;ext&gt;.ico (a crisp multi-res icon, generated by tools/genfileicons.ps1),
/// and is made the per-user default handler so Explorer paints that icon. A version marker
/// keeps it idempotent: it only rewrites the keys once per AssocVersion / exe path.
/// </summary>
internal static class FileAssoc
{
    // Bump when the registration scheme changes so an upgrade re-registers exactly once.
    private const int AssocVersion = 4;

    private const string ProgIdPrefix = "EpicRpf.";    // per-extension: EpicRpf.ydr, EpicRpf.ytd, …
    private const string EpicProgId   = "EpicRpf.Epic"; // our own .epic package format
    private const string MarkerKey    = @"Software\Classes\EpicRpf";

    // GTA-specific game/resource extensions the app can view/edit. Each gets its own icon +
    // becomes the default handler. (.epic is handled separately, with its package icon.)
    // Deliberately GTA-only — generic types (.xml/.txt/.ini/.lua/.cfg) are NOT hijacked.
    // Every entry here has a matching wwwroot/icons/<ext>.ico (else it falls back to file.ico,
    // which is exactly what the in-app tree shows for it too).
    private static readonly string[] Exts =
    {
        ".ydr", ".ydd", ".yft", ".ytd", ".ypt", ".ymt", ".ymap", ".ytyp", ".ymf",
        ".meta", ".pso", ".rbf", ".gfx", ".ynd", ".ycd", ".ybn", ".awc", ".rel",
        ".dat", ".cut", ".ynv", ".yed", ".yfd", ".ypdb", ".mrf", ".yld", ".gxt2",
    };

    public static void EnsureRegistered()
    {
        try
        {
            string exe = Process.GetCurrentProcess().MainModule?.FileName ?? "";
            if (string.IsNullOrEmpty(exe)) return;
            string command = $"\"{exe}\" \"%1\"";
            string iconsDir = Path.Combine(Path.GetDirectoryName(exe) ?? "", "wwwroot", "icons");

            // Idempotency: skip when this exe already registered the current scheme.
            using (var mk = Registry.CurrentUser.OpenSubKey(MarkerKey))
                if (mk?.GetValue("AssocVersion") is int v && v == AssocVersion
                    && string.Equals(mk.GetValue("AssocExe") as string, exe, StringComparison.OrdinalIgnoreCase))
                    return;

            // .epic — our own format: its own package icon + default handler.
            string epicIco = Path.Combine(iconsDir, "epic.ico");
            RegisterProgId(EpicProgId, "Epic RPF extension", File.Exists(epicIco) ? epicIco : null, exe, command);
            AddOpenWith(".epic", EpicProgId);
            SetDefault(".epic", EpicProgId);

            // Generic extensions — each with its own icon, made the per-user default so the
            // desktop shows the matching glyph instead of a single shared app icon.
            foreach (var ext in Exts)
            {
                string baseName = ext.TrimStart('.');
                string ico = Path.Combine(iconsDir, baseName + ".ico");
                if (!File.Exists(ico)) ico = Path.Combine(iconsDir, "file.ico");   // fallback glyph
                string progId = ProgIdPrefix + baseName;                           // EpicRpf.ydr

                RegisterProgId(progId, $"GTA V {baseName.ToUpperInvariant()} file",
                    File.Exists(ico) ? ico : null, exe, command);
                AddOpenWith(ext, progId);
                SetDefault(ext, progId);
                ClearOwnUserChoice(ext);   // drop any stale "always open with Epic RPF" pinning the old icon
            }

            using (var mk = Registry.CurrentUser.CreateSubKey(MarkerKey))
            {
                mk.SetValue("AssocVersion", AssocVersion, RegistryValueKind.DWord);
                mk.SetValue("AssocExe", exe);
            }

            SHChangeNotify(0x08000000, 0x1000, IntPtr.Zero, IntPtr.Zero);   // SHCNE_ASSOCCHANGED | SHCNF_FLUSH
            RefreshIconCache();   // evict stale cached icons (e.g. an old shared app icon) so the new per-ext icons show
        }
        catch { /* association is a convenience; never block startup */ }
    }

    // Tell the shell to rebuild its icon cache. After an upgrade, Explorer may keep showing
    // the previously cached icon for an extension even though the registry now points at a new
    // one; this is the standard, non-disruptive way Windows itself refreshes icons (no Explorer
    // restart). Runs only when we (re)register, i.e. once per AssocVersion.
    private static void RefreshIconCache()
    {
        try
        {
            Process.Start(new ProcessStartInfo
            {
                FileName = "ie4uinit.exe",
                Arguments = "-show",
                UseShellExecute = false,
                CreateNoWindow = true,
            });
        }
        catch { }
    }

    // Create/refresh a ProgId: friendly name, DefaultIcon (per-ext .ico, else the exe), open command.
    private static void RegisterProgId(string progId, string desc, string? iconPath, string exe, string command)
    {
        using var prog = Registry.CurrentUser.CreateSubKey($@"Software\Classes\{progId}");
        prog.SetValue(null, desc);
        using (var icon = prog.CreateSubKey("DefaultIcon"))
            icon.SetValue(null, iconPath != null ? $"\"{iconPath}\",0" : $"\"{exe}\",0");
        using var cmd = prog.CreateSubKey(@"shell\open\command");
        cmd.SetValue(null, command);
    }

    // List us under the extension's "Open with" without removing other apps.
    private static void AddOpenWith(string ext, string progId)
    {
        using var k = Registry.CurrentUser.CreateSubKey($@"Software\Classes\{ext}\OpenWithProgids");
        k.SetValue(progId, Array.Empty<byte>(), RegistryValueKind.None);
    }

    // Per-user default handler (drives the icon too) — the classic (Default) value of HKCU\…\.ext.
    private static void SetDefault(string ext, string progId)
    {
        using var def = Registry.CurrentUser.CreateSubKey($@"Software\Classes\{ext}");
        def.SetValue(null, progId);
    }

    // Explorer's UserChoice ("Always open with…") overrides the classic default, including the
    // icon. Only clear it when it points at one of OUR ProgIds (so the new per-ext default +
    // icon take effect); never touch a choice the user made for another app.
    private static void ClearOwnUserChoice(string ext)
    {
        try
        {
            string baseP = $@"Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\{ext}";
            using (var uc = Registry.CurrentUser.OpenSubKey($@"{baseP}\UserChoice"))
            {
                var pid = uc?.GetValue("ProgId") as string;
                if (pid == null || !pid.StartsWith("EpicRpf", StringComparison.OrdinalIgnoreCase)) return;
            }
            Registry.CurrentUser.DeleteSubKeyTree($@"{baseP}\UserChoice", throwOnMissingSubKey: false);
        }
        catch { /* protected on some builds; the classic default still applies otherwise */ }
    }

    [DllImport("shell32.dll")] private static extern void SHChangeNotify(int eventId, uint flags, IntPtr a, IntPtr b);
}
